export const DUMMY_PRODUCTS = [
  {
    product_id: 1,
    name: "Tấm ốp tường PVC vân đá",
    code: "PVC-001",
    product_image: "https://via.placeholder.com/400x300?text=PVC+Van+Da",
    price: 0,
    short_desc: "Tấm ốp tường PVC vân đá cao cấp, chống nước, dễ thi công.",
    material: "Nhựa PVC",
    technology: "Ép nhiệt hiện đại",
    color: "Trắng, Vàng, Xám",
    dimensions: "1220x2440mm",
    warranty: "12 tháng",
    transport: "Toàn quốc",
    characteristic: "Chống nước, chống ẩm, bền màu.",
    categories: { category_name: "Ốp tường" },
  },
  {
    product_id: 2,
    name: "Tấm ốp trần Nano",
    code: "NANO-002",
    product_image: "https://via.placeholder.com/400x300?text=Nano+Op+Tran",
    price: 350000,
    short_desc: "Tấm ốp trần Nano cách âm, cách nhiệt, mẫu mã đa dạng.",
    material: "Nhựa Nano",
    technology: "Công nghệ Nano phủ UV",
    color: "Gỗ, Trắng, Đen",
    dimensions: "3000x195mm",
    warranty: "24 tháng",
    transport: "Miễn phí nội thành",
    characteristic: "Cách âm, cách nhiệt, dễ vệ sinh.",
    categories: { category_name: "Ốp trần" },
  },
  {
    product_id: 3,
    name: "Tấm ốp lam sóng",
    code: "LAM-003",
    product_image: "https://via.placeholder.com/400x300?text=Lam+Song",
    price: 420000,
    short_desc: "Tấm ốp lam sóng trang trí nội thất sang trọng.",
    material: "Nhựa tổng hợp",
    technology: "Ép đùn",
    color: "Nâu, Vàng nhạt",
    dimensions: "3000x200mm",
    warranty: "18 tháng",
    transport: "Giao hàng tận nơi",
    characteristic: "Chống cong vênh, không mối mọt.",
    categories: { category_name: "Lam sóng" },
  },
];